name: bookly_full_app_mvvm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  go_router: ^14.8.1
  google_fonts: ^6.1.0
  animate_do: ^4.2.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  dartz: ^0.10.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  google_sign_in: ^6.1.6
  get_it: ^8.0.3
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.2.2
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  url_launcher: ^6.2.1
  share_plus: ^10.1.4
  giffy_dialog: ^2.0.0+2
  image_picker: ^1.0.4
  firebase_storage: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

