name: bookly_full_app_mvvm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dartz: ^0.10.1
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6
  get_it: ^7.6.4
  cloud_firestore: ^4.13.0
  shared_preferences: ^2.2.2
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

