// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNFUdXp7SUQVVsbnTlf-ox-HWeCpvF4UY',
    appId: '1:192273553338:web:fcaf39e689b93c1c2caf83',
    messagingSenderId: '192273553338',
    projectId: 'bookly-app-e7d40',
    authDomain: 'bookly-app-e7d40.firebaseapp.com',
    storageBucket: 'bookly-app-e7d40.appspot.com',
    measurementId: 'G-PLREFL7S40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCVqlKCAvpZvwb-qa_FKvrOoPIrh0fd_A',
    appId: '1:192273553338:android:a1b2a60621ab78aa2caf83',
    messagingSenderId: '192273553338',
    projectId: 'bookly-app-e7d40',
    storageBucket: 'bookly-app-e7d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RYj5ee04B6-wKC9AL6EZQKDCyIR60EA',
    appId: '1:192273553338:ios:4154a74083088b012caf83',
    messagingSenderId: '192273553338',
    projectId: 'bookly-app-e7d40',
    storageBucket: 'bookly-app-e7d40.appspot.com',
    iosBundleId: 'com.example.booklyFullAppMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4RYj5ee04B6-wKC9AL6EZQKDCyIR60EA',
    appId: '1:192273553338:ios:a59d80c3937f72942caf83',
    messagingSenderId: '192273553338',
    projectId: 'bookly-app-e7d40',
    storageBucket: 'bookly-app-e7d40.appspot.com',
    iosBundleId: 'com.example.booklyFullAppMvvm.RunnerTests',
  );
}
